model:
  # name of the model
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps at each stage of UNet encoder
  f_maps: [16, 32, 64, 128, 256]
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
# loss function to be used during training
loss:
  # use binary cross-entropy combined with the Dice loss
  name: BCEDiceLoss
  # skip the last channel in the target (i.e. when last channel contains data not relevant for the loss)
  skip_last_target: true
  # ignore a given label in the gradient computation
  ignore_index: 1
optimizer:
  # initial learning rate
  learning_rate: 0.0001
  # weight decay
  weight_decay: 0.00001
# evaluation metric
eval_metric:
  # use AdaptedRandError metric
  name: BoundaryAdaptedRandError
  # probability maps threshold
  threshold: 0.4
  # use the last target channel to compute the metric
  use_last_target: true
  # ignore a given label in the metric computation
  ignore_index: 1
# learning rate scheduler configuration
lr_scheduler:
  # reduce learning rate when training stagnates
  name: ReduceLROnPlateau
  # make sure to use the 'min' mode cause lower AdaptedRandError is better
  mode: min
  # reduce by a factor of 5
  factor: 0.2
  # reduce LR if the validation metric does not improve after 'patience' number of validation runs
  patience: 25
trainer:
  # model with lower eval score is considered better
  eval_score_higher_is_better: False
  # path to the checkpoint directory (this is where the model is saved)
  checkpoint_dir: '/g/kreshuk/wolny/workspace/takafumi_data/unet_072021'
  # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  resume: null
  # how many iterations between validations
  validate_after_iters: 250
  # how many iterations between tensorboard logging
  log_after_iters: 250
  # max number of epochs
  max_num_epochs: 50000
  # max number of iterations
  max_num_iters: 50000
# Configure training and validation loaders
loaders:
  batch_size: 1
  # how many subprocesses to use for data loading
  num_workers: 4
  # path to the raw data within the H5
  raw_internal_path: raw
  # path to the the label data withtin the H5
  label_internal_path: label
  # configuration of the train loader
  train:
    # paths to the training datasets
    file_paths:
      - '/g/kreshuk/wolny/Datasets/Takafumi/072021/train'

    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: SliceBuilder
      patch_shape: [80, 100, 100]
      stride_shape: [5, 10, 10]

    # data augmentation pipeline
    transformer:
      raw:
        - name: Standardize
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY plane due to anisotropy
          axes: [[2, 1]]
          angle_spectrum: 45
          mode: reflect
        - name: ElasticDeformation
          spline_order: 3
          execution_probability: 0.3
        - name: GaussianBlur3D
          execution_probability: 0.5
        - name: AdditiveGaussianNoise
          execution_probability: 0.25
        - name: AdditivePoissonNoise
          execution_probability: 0.25
        - name: ToTensor
          expand_dims: true
      label:
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY plane due to anisotropy
          axes: [[2, 1]]
          angle_spectrum: 45
          mode: reflect
        - name: ElasticDeformation
          spline_order: 0
          execution_probability: 0.3
        - name: StandardLabelToBoundary
          # append original ground truth labels to the last channel (to be able to compute the eval metric)
          append_label: true
        - name: ToTensor
          expand_dims: false

  # configuration of the val loader
  val:
    # paths to the val datasets
    file_paths:
      - - '/g/kreshuk/wolny/Datasets/Takafumi/072021/val'

    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: SliceBuilder
      patch_shape: [111, 133, 133]
      stride_shape: [111, 133, 133]

    # data augmentation
    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
      label:
        - name: StandardLabelToBoundary
          append_label: true
        - name: ToTensor
          expand_dims: false